// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXezua-W152nPIcobJYNMnzM6r6qp684',
    appId: '1:672257039054:web:7755dcae5d683f2cbd4e9f',
    messagingSenderId: '672257039054',
    projectId: 'fir-notification-d424b',
    authDomain: 'fir-notification-d424b.firebaseapp.com',
    storageBucket: 'fir-notification-d424b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqNuk3HS3mOyEPcopWPn9a3Sc0dMH-ZA',
    appId: '1:672257039054:android:71a05171058f71afbd4e9f',
    messagingSenderId: '672257039054',
    projectId: 'fir-notification-d424b',
    storageBucket: 'fir-notification-d424b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCTByYfvtnX2j2SyGybw6ZqWqvIUIY30',
    appId: '1:672257039054:ios:e26029f217d41aa5bd4e9f',
    messagingSenderId: '672257039054',
    projectId: 'fir-notification-d424b',
    storageBucket: 'fir-notification-d424b.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

}